version: '2'
services:
    jhipsterleftmenu-app:
        image: jhipsterleftmenu
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterleftmenu-mysql:3306/jhipsterleftmenu?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterleftmenu-mysql:
        extends:
            file: mysql.yml
            service: jhipsterleftmenu-mysql
